export const work = {
  featured: {
    client: "Priya Sharma",
    project: "Fashion Brand Launch",
    campaign: "Instagram Reels Campaign",
    quote: "StanMerk transformed our raw footage into viral content. Our engagement increased by 400% in just 2 weeks!",
    avatar: "/avatars/priya.jpg",
    role: "Founder",
    company: "StyleHub",
    stats: [
      { label: "Engagement", value: "+400%", highlight: false },
      { label: "Views", value: "2.5M", highlight: true },
      { label: "Followers", value: "+50K", highlight: false },
    ],
    media: "/work/featured.mp4",
    poster: "/work/featured-poster.jpg",
    platform: "Reels",
    views: "2.5M",
  },
  cases: [
    {
      title: "Tech Review Channel",
      category: "YouTube Long-form",
      media: "https://res.cloudinary.com/dlvgf55ti/video/upload/q_auto/f_auto/1st_yxid4g.mp4",
      poster: "https://res.cloudinary.com/dlvgf55ti/video/upload/so_3/q_auto/f_auto/1st_yxid4g.jpg",
      platform: "YouTube",
      views: "850K",
      growth: "+320%",
    },
    {
      title: "Fitness Coach Brand",
      category: "Reels Campaign",
      media: "https://res.cloudinary.com/dlvgf55ti/video/upload/q_auto/f_auto/2nd_xmpnen.mp4",
      poster: "https://res.cloudinary.com/dlvgf55ti/video/upload/so_3/q_auto/f_auto/2nd_xmpnen.jpg",
      platform: "Reels",
      views: "1.2M",
      growth: "+280%",
    },
    {
      title: "Food Creator Portfolio",
      category: "Shorts Series",
      media: "https://res.cloudinary.com/dlvgf55ti/video/upload/q_auto/f_auto/3rd_h8fphf.mp4",
      poster: "https://res.cloudinary.com/dlvgf55ti/video/upload/so_3/q_auto/f_auto/3rd_h8fphf.jpg",
      platform: "Shorts",
      views: "680K",
      growth: "+195%",
    },
  ],
};
